#!/usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $EMPIREDIR = "/home/empowner/empire";
my $SCREENCMD = "/usr/bin/screen";
my $EMPIREEXE = "nohup /home/empowner/empire/sbin/emp_server\&";

# No changes below here...

my $exists = "";

# Set ENV vars
$ENV{'TERM'} = "xterm-256color";

my $running=`ps ax|grep emp_server|grep -v grep`;

# check if Empire server process is running
if ($running ne "")
{
	print ("Startupscript already running...\n");
	exit (0);
}

while (-1)
{
	chdir $EMPIREDIR;
	# check if Empire server process is running
	$running=`ps ax|grep emp_server|grep -v grep`;
	if ($running eq "")
	{
		print "Empire server not running\n";
		# See if they want the server started
		if (! -f "$EMPIREDIR/nostart")
		{
			# The Log Entry
			my $datestring = localtime();
			my $TIME="Empire server Down, Restarting: $datestring";
			open(OUTF, ">>$EMPIREDIR/EmpireServerScreen.log") || die "Unable to open $EMPIREDIR/EmpireServerScreen.log for appending";
			print (OUTF "$TIME\n");
			close($OUTF);
			chdir $EMPIREDIR;
			print "Starting screen process\n";
			system("$SCREENCMD -fa -S EmpireServer -d -U -m $EMPIREEXE");
		}
	}
	# Sleep for a minute before checking again
	sleep(60);
}
exit(0);
